app/models/supplier.py
from app import db


class Supplier(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    Name = db.Column(db.String, nullable=False)
    Contact = db.Column(db.String, nullable=True)
    Address = db.Column(db.String, nullable=True)
    Comment = db.Column(db.String, nullable=True)
    # Products = db.relationship('Product', backref='supplier', lazy=True)

app/supplier/__init__.py
from flask import Flask, Blueprint
bp = Blueprint('supplier',__name__)


from app.supplier import routes

app/supplier/routes.py
from flask_login import login_required
from app.supplier import bp
from flask import render_template, request, redirect, url_for
from app.models.supplier import Supplier
from app import db, update_qty_on_expiry


# Create Supplier
@bp.route('/add', methods=['POST'])
@login_required
def add_supplier():
    update_qty_on_expiry()
    name = request.form['name']
    contact = request.form['contact']
    address = request.form['address']
    comment = request.form['comment']

    # Validation checks can be added here

    supplier = Supplier(Name=name, Contact=contact, Address=address, Comment=comment)
    db.session.add(supplier)
    db.session.commit()
    return redirect(url_for('supplier.index'))

# Read Supplier
@bp.route('/<int:id>')
@login_required
def get_supplier(id):
    supplier = Supplier.query.get(id)
    return render_template('supplier/detail.html', supplier=supplier)

# Update Supplier
@bp.route('/update/<int:id>', methods=['POST'])
@login_required
def update_supplier(id):
    supplier = Supplier.query.get(id)
    supplier.Name = request.form['name']
    supplier.Contact = request.form['contact']
    supplier.Address = request.form['address']
    supplier.Comment = request.form['comment']
    db.session.commit()
    return redirect(url_for('supplier.index'))

# Delete Supplier
@bp.route('/delete/<int:id>')
@login_required
def delete_supplier(id):
    supplier = Supplier.query.get(id)
    db.session.delete(supplier)
    db.session.commit()
    return redirect(url_for('supplier.index'))

# Search Supplier
@bp.route('/search')
@login_required
def search_supplier():
    keyword = request.args.get('q','')
    suppliers = Supplier.query.filter(Supplier.Name.ilike(f'%{keyword}%')).all()
    return render_template('supplier/index.html', suppliers=suppliers)

# Pagination Supplier
@bp.route('/')
@login_required
def index():
    page = request.args.get('page', 1, type=int)
    per_page =  request.args.get('per_page', 10, type=int)
    suppliers = Supplier.query.paginate(page = page, per_page = per_page, error_out=False)
    return render_template('supplier/index.html', suppliers=suppliers)

app/templates/supplier/detail.html
{% extends 'base.html' %}
{% block nav_title %} Supplier Overview > <a href="{{url_for('supplier.get_supplier',id = supplier.id)}}">Supplier</a>{% endblock %}
{% block css_style %}
    <link rel="stylesheet" href="{{url_for('static',filename='css/grid.css')}}"> 
    <link rel="stylesheet" href="{{url_for('static',filename='css/form.css')}}"> 
{% endblock %}
{% block nav_inventory %}active{% endblock %}
{% block content %}
<div class="form-container">
    <h3>Edit Supplier</h3>

    <form method="POST" action="{{ url_for('supplier.update_supplier',id = supplier.id) }}">
        <label for="name">Name:</label><br>
        <input type="text" id="name" name="name" value="{{ supplier.Name if supplier else '' }}" required><br><br>
        
        <label for="contact">Contact:</label><br>
        <input type="text" id="contact" name="contact" value="{{ supplier.Contact if supplier else '' }}" required><br><br>
        
        <label for="address">Address:</label><br>
        <input type="text" id="address" name="address" value="{{ supplier.Address if supplier else '' }}" required><br><br>
        
        <label for="comment">Comment:</label><br>
        <textarea id="comment" name="comment" cols="4" required>{{ supplier.Comment if supplier else '' }}</textarea><br><br>
        <input type="submit" value="Submit">
    </form>
</div>
{% endblock %}

app/templates/supplier/index.html
{% extends 'base.html' %}
{% block nav_title %} Supplier Overview{% endblock %}

{% block css_style %} 
    <link rel="stylesheet" href="{{url_for('static',filename='css/table.css')}}"> 
    <link rel="stylesheet" href="{{url_for('static',filename='css/form.css')}}"> 
    <link rel="stylesheet" href="{{url_for('static',filename='css/modal.css')}}"> 
    <link rel="stylesheet" href="{{url_for('static',filename='css/modal.css')}}"> 
{% endblock %}
{% block nav_supplier %}active{% endblock %}


{% block content %}
{% for role in current_user.roles if role.name == 'admin' %}
<button class="button success" onclick="openModal()">Create</button>
<div class="modal-container" id="create_product">
    <div class="modal-content">
        <span class="close-button" onclick="closeModal()">&times;</span>
        <div class="form-container">
            <h3>Create Supplier</h3>
    
            <form method="POST" action="{{ url_for('supplier.add_supplier') }}">
                <label for="name">Name:</label><br>
                <input type="text" id="name" name="name" required><br><br>
                
                <label for="contact">Contact:</label><br>
                <input type="text" id="contact" name="contact" required><br><br>
                
                <label for="address">Address:</label><br>
                <input type="text" id="address" name="address" required><br><br>
                
                <label for="comment">Comment:</label><br>
                <textarea id="comment" name="comment" cols="4"></textarea><br><br>
                <input type="submit" value="Submit">
            </form>
        </div>
    </div>
</div>
{% endfor %}

<div class="table-container maxheight-800 scrollable">
    <table>
        <tr>
            <th>Name</th>
            <th>Contact</th>
            <th>Address</th>
            <th>Comment</th>
            {% for role in current_user.roles if role.name == 'admin' %}
            <th>Action</th>{% endfor %}

        </tr>
        {% for supplier in suppliers %}
        <tr>
            <td><a href="{{url_for('supplier.get_supplier',id = supplier.id)}}">{{supplier.Name}}</a></td>
            <td>{{supplier.Contact}}</td>
            <td>{{supplier.Address}}</td>
            <td>{{supplier.Comment}}</td>
            {% for role in current_user.roles if role.name == 'admin' %}
            <td>
                <a href="{{url_for('supplier.delete_supplier',id = supplier.id)}}" onclick="return confirm('Are you sure you want to delete this item?')"><i class='bx bx-trash-alt'></i></a>
            </td>{% endfor %}
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

{% block jscontent %}
<script src="{{url_for('static',filename='/js/modal.js')}}">

</script>
{% endblock %}