app/models/cashflow.py
from app.extensions import db

class Cashflow(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    particulars = db.Column(db.String(255), nullable=False)
    date = db.Column(db.DateTime, nullable=False)

    debit = db.Column(db.Float, default=0)
    credit = db.Column(db.Float, default=0)
    balance = db.Column(db.Float, default=0)
    remarks = db.Column(db.String(255))

    def __repr__(self):
        return f"Cashflow('{self.particulars}', '{self.date}', '{self.debit}', '{self.credit}', '{self.balance}', '{self.remarks}')"

app/auth.py
from datetime import datetime
from flask import Blueprint, current_app, flash,render_template,redirect, request, session, url_for
from flask_login import current_user, login_user, login_required, logout_user
from flask_wtf import FlaskForm

# from werkzeug.security import generate_password_hash, check_password_hash
from app.extensions import db,login_manager
from app.models.user import Role, User, UserRoles

from flask_principal import Principal, Identity, AnonymousIdentity, identity_changed
from werkzeug.security import  check_password_hash


from wtforms import BooleanField, IntegerField, PasswordField, RadioField, SelectField, StringField, ValidationError
from wtforms.validators import InputRequired,Email, Length, EqualTo,NumberRange,DataRequired

auth = Blueprint('auth', __name__)
 

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[InputRequired(), Email(), Length(max=50)])
    password = PasswordField('Password', validators=[InputRequired(), Length(min=5)])
 
class ForgetForm(FlaskForm):
    email = StringField('Email', validators=[InputRequired(), Email(), Length(max=50)])
    pins = IntegerField('Security Pin', validators=[InputRequired(),Length(min=6,max=6)])
    
    def validate_email(self, field):
        if not User.query.filter(User.Email == field.data, User.pins == field.data).first():
            raise ValidationError('Email doest not existing.')



@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

@auth.route('/login', methods=['GET', 'POST']  )
def login():

    form = LoginForm()
    print(form.validate_on_submit())
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        remember = True if request.form.get('remember') else False
        user = User.query.filter_by(Email=email).first()
        # check if the user actually exists
        # take the user-supplied password, hash it, and compare it to the hashed password in the database
        if not user or not user.check_password(password):
            flash('Please check your login details and try again.','error')
            return redirect(url_for('auth.login')) # if the user doesn't exist or password is wrong, reload the page
        
        user.Last_Login = datetime.now()
        db.session.commit()
        login_user(user, remember=remember)


        # Tell Flask-Principal the identity changed
        identity_changed.send(current_app._get_current_object(),
                                  identity=Identity(user.id))


        return redirect(url_for('dashboard'))
    

    return render_template('login/login.html',form = form)


@auth.route('/signup',methods=["GET"])
def signup():
    return redirect(url_for('user.create_staff'))
        



@auth.route('/logout')
@login_required
def logout():
    logout_user()

    # Remove session keys set by Flask-Principal
    for key in ('identity.name', 'identity.auth_type'):
        session.pop(key, None)

    # Tell Flask-Principal the user is anonymous
    identity_changed.send(current_app._get_current_object(),
                          identity=AnonymousIdentity())
    return redirect(url_for('auth.login'))




@auth.route('/general_reset_password', methods=['POST'])
def general_reset_password():
    if request.method == 'POST':
        email = request.form.get('email')
        digits = request.form.get('secret_pin')
        existing_user = User.query.filter(User.Email == email,User.pins == digits).first()
        if not existing_user:
            flash("Email not existed")
            return redirect(url_for('auth.login'))

        existing_user.set_password('123456')
        db.session.commit()
        flash('Password has been reset, Temporary password:123456 \nPlease change your password for security')

    return redirect(url_for('auth.login'))


# @auth.route('/set_pins', methods=['POST'])
# def set_pins():
#     id = request.form.get('id')
#     pins = request.form.get('pins')
#     user = User.query.filter(User.id == int(id)).first()
#     user.pins =pins

#     db.session.commit()
#     return redirect(url_for('main.profile'))

app/cashflow/routes.py
from datetime import date, datetime, time, timedelta
import math
import string
from flask import Flask, Blueprint, redirect, render_template, request, url_for
from numpy import equal
from app import update_qty_on_expiry
from app.extensions import db
from app.models.cashflow import Cashflow
bp = Blueprint('cashflow',__name__)

def init_current_month():
    update_qty_on_expiry()
    first_day_of_month, last_day_of_month, firstday_of_previous_month, last_month_end = get_month_value(datetime.now())

    # Filter last record of previous month
    last_month_records = Cashflow.query.filter(
        Cashflow.date >= firstday_of_previous_month,
        Cashflow.date < first_day_of_month
    ).order_by(Cashflow.date.desc()).all()

    # Check the last balance of previous month, if record exist then assign LAST BALANCE
    last_debit = 0
    if last_month_records:

        last_debit = last_month_records[0].balance

    #create first record of current month
    if not Cashflow.query.filter(Cashflow.date == first_day_of_month).first():
        new_cashflow = Cashflow(particulars = "balance b/f",date = first_day_of_month, debit=last_debit)
        db.session.add(new_cashflow)
        db.session.commit()
        new_cashflow.balance = new_cashflow.debit - new_cashflow.credit
        db.session.commit()


@bp.route('/', methods=['GET'])
def index():
    inncashflow()
    print("tyesss")
    selected_month =  datetime.today() if not request.args.get('date') else datetime.strptime(request.args.get('date'),'%Y-%m').replace(day=1).date()
    selected_month = datetime.strftime(selected_month,'%Y-%m-%d')
    selected_month = datetime.strptime(selected_month,"%Y-%m-%d").replace(day=1,hour=0,minute=0,second=0)

    first_day_of_month, last_day_of_month, _,_ = get_month_value(datetime.now())
    if not Cashflow.query.filter(Cashflow.date == first_day_of_month).first():
        init_current_month()

    check_last_month_balance(first_day_of_month)
    
    first_day_of_month, last_day_of_month, firstday_of_previous_month, lastday_of_previous_month = get_month_value(selected_month)
    cashflows = Cashflow.query.filter(Cashflow.date >= first_day_of_month,Cashflow.date<=last_day_of_month).order_by(Cashflow.date).all()
    return render_template('cashflow.html',cashflows = cashflows,date = datetime.strftime(selected_month,'%Y-%m'))



def get_month_value(date):
    
    '''
    return 4 value,
    return type: Datetime
    '''
    
    # first day of current month
    first_day_month = datetime.strftime(date,"%Y-%m-%d %H:%M:%S")
    first_day_month = datetime.strptime(first_day_month,"%Y-%m-%d %H:%M:%S").replace(day=1,hour=0,minute=0,second=0)

    #last day of current month
    next_month = first_day_month.replace(day=28) + timedelta(days=4)
    lastday_of_month = next_month.replace(day=1) - timedelta(days=1)
    lastday_of_month = lastday_of_month.replace(hour=23,minute=59,second=59)

    # get first day and last day of previous month
    lastday_of_previous_month = first_day_month.replace(day=1) - timedelta(days=1)
    lastday_of_previous_month = lastday_of_previous_month.replace(hour=23,minute=59,second=59)
    firstday_of_previous_month = lastday_of_previous_month.replace(day=1,hour=0,minute=0,second=0)
    return first_day_month, lastday_of_month, firstday_of_previous_month, lastday_of_previous_month

def round_to(value, decimals=9):
    return eval(f"{{:.{decimals}f}}".format(value))

def check_last_month_balance(date):
    first_day_month, lastday_of_month, firstday_of_previous_month, lastday_of_previous_month = get_month_value(date)
    cashflow = Cashflow.query.filter(Cashflow.date == first_day_month).first()
    last_record = get_last_record_before_date(first_day_month)
    if last_record:
        cashflow.debit = float(last_record.balance)
        cashflow.balance = float(cashflow.debit)
        db.session.commit()

            # Update balance for affected records
        affected_records = Cashflow.query.filter(Cashflow.date >= cashflow.date,Cashflow.date<=lastday_of_month).order_by(Cashflow.date).all()
        for record in affected_records:
            if record.id != cashflow.id:
                last_record = get_last_record_before_date(record.date)
                # balance_change = cashflow.balance - last_record.balance
                # record.balance += balance_change
                record.balance = last_record.balance + (record.debit - record.credit)
            db.session.commit()
    else:
        print("NO previous record", last_record)
        # print(cashflow.balance)






@bp.route('/detail',methods=["GET"])
# @bp.route('/detail/<int:id>',methods=["GET"])
def record_detail():
    id = request.args.get('id',type=int)
    cashflow = Cashflow.query.filter(Cashflow.id == id).first()
    return render_template('cashflow_detail.html',cashflow = cashflow)




def get_last_record_before_date(date):
    return Cashflow.query.filter(Cashflow.date < date).order_by(Cashflow.date.desc()).first()

@bp.route('/', methods=['POST'])
def add_cashflow():


    specific_date = datetime.strftime(datetime.today(),"%Y-%m-%d %H:%M:%S")
    specific_date = datetime.strptime(specific_date,"%Y-%m-%d %H:%M:%S")
    last_record = get_last_record_before_date(specific_date)
    
    # print(f"{last_record.date} + {last_record.balance}")
    if last_record:
        last_balance = last_record.balance
    else:
        last_balance = 0

    new_cashflow = Cashflow(
        particulars=request.form['particulars'],
        date=specific_date,
        debit=request.form['debit'],
        credit=request.form['credit'],
        remarks=request.form['remark']
    )
    new_cashflow.balance =float(last_balance) + float(new_cashflow.debit) - float(new_cashflow.credit)
    db.session.add(new_cashflow)
    db.session.commit()

    affected_records = Cashflow.query.filter(Cashflow.date > specific_date).order_by(Cashflow.date).all()
    for record in affected_records:
            record.balance = record.balance + new_cashflow.debit - new_cashflow.credit

    db.session.commit()
    return redirect(url_for('cashflow.index'))




@bp.route('/insert_record', methods=['POST'])
def insert_cashflow():
    new_date = datetime.strptime(request.form['new_date']+ ' ' + request.form['new_time'],'%Y-%m-%d %H:%M:%S')
    last_record = get_last_record_before_date(new_date)
    _,lastday_of_month,_,_ = get_month_value(new_date)
    try:
        new_cashflow = Cashflow(
            particulars=request.form['particulars'],
            date=new_date,
            debit=request.form['debit'],
            credit=request.form['credit'],
            remarks=request.form['remark']
        )
        db.session.add(new_cashflow)
        db.session.commit()

        
        affected_records = Cashflow.query.filter(Cashflow.date > last_record.date, Cashflow.date <= lastday_of_month).order_by(Cashflow.date).all()
        
        for record in affected_records:
            last_record = get_last_record_before_date(record.date)
            record.balance = last_record.balance + (record.debit - record.credit)
                    # record.balance = last_record.balance + (record.debit - record.credit)

        db.session.commit()
    except Exception as e:
        db.session.rollback()
        return f"error: {str(e)}", 500

    return redirect(url_for('cashflow.index'))

def insert_to_cashflow(particular='',debit=0.00,credit=0.00,remark=''):
    print('yessss')
    date = datetime.strftime(datetime.now(),'%Y-%m-%d %H:%M:%S')
    date = datetime.strptime(date,'%Y-%m-%d %H:%M:%S')
    first_day_of_month, last_day_of_month, _,_= get_month_value(date)
    if not Cashflow.query.filter(Cashflow.date == first_day_of_month).first():
        init_current_month()
        check_last_month_balance(date)

    last_record = get_last_record_before_date(date)
    new_cashflow = Cashflow(
        particulars = particular,
        debit = debit,
        credit = credit,
        date = date,
        remarks = remark
    )
    db.session.add(new_cashflow)
    db.session.commit()
    new_cashflow.balance = last_record.balance + (new_cashflow.debit - new_cashflow.credit)
    db.session.commit()
    print('end eeeee')
    

#This Method is used to update the record without date
@bp.route('/detail',methods=["POST"])
def update_record():
    id = request.args.get('id',default=None,type=int)
    if not id:
        return 404
    # Find current record
    cashflow = Cashflow.query.filter_by(id=id).first_or_404()
    #get previous record
    previous_record = Cashflow.query.filter(Cashflow.date<cashflow.date,Cashflow.date>=cashflow.date.replace(day=1,hour=0,minute=0,second=0)).order_by(Cashflow.date.desc()).first()
    last_balance = 0
    if previous_record:
        last_balance = previous_record.balance #get previous balance


    new_credit = request.form["new_credit"]
    new_debit = request.form["new_debit"]
    new_remark = request.form["new_remark"]

    old_amount = cashflow.balance
    new_balance = float(last_balance) + float(new_debit) - float(new_credit)
    cashflow.balance = new_balance
    cashflow.particulars = request.form['new_particular']
    cashflow.debit = new_debit
    cashflow.credit = new_credit
    cashflow.remarks = new_remark
    db.session.commit()
    


    # Update balance for affected records
    affected_records = Cashflow.query.filter(Cashflow.date >= cashflow.date).all()
    for record in affected_records:
        if record.id != cashflow.id:
            balance_change = new_balance - old_amount
            record.balance += balance_change
    db.session.commit()
    return redirect(url_for('cashflow.index'))


#This Method is used to update the record date
@bp.route('/update', methods=['POST'])
def update_cashflow_date():
    id = request.args.get('id')
    cashflow = Cashflow.query.get_or_404(id)
    new_date = datetime.strptime(request.form['new_date']+ ' ' + request.form['new_time'],'%Y-%m-%d %H:%M:%S')
    old_date = cashflow.date

    if not new_date:

app/category/__init__.py
from flask import Flask, Blueprint
bp = Blueprint('category',__name__)


from app.category import routes

app/product/__init__.py
from flask import Flask, Blueprint
bp = Blueprint('product',__name__)


from app.product import product_routers,inventory_routers,loss_routers

app/user/__init__.py
from flask import Flask, Blueprint
bp = Blueprint('user',__name__)


from app.user import routes

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>S-Mart Inventory System</title>
    <link rel="stylesheet" href="{{url_for('static',filename='css/button.css')}}"> 
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/responsive.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/cards.css')}}">

    <link rel="stylesheet" href="{{url_for('static',filename='css/preloader.css')}}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    {% block css_style %}
    {% endblock %}
    <style>
        .logout{
            padding: .5rem 1rem
        }
        .logout:hover{
            background: rgba(212, 212, 212, 0.3);
            border-radius: 10px;
            
        }
    </style>

</head>
<body>


    <div class="wrapper">

        <aside class="opened" id="aside">
            <div class="sidebar">
                <div class="brand-items">
                    <div class="brand-logo">
                        <img src="{{url_for('static',filename='/img/gear-loader.gif')}}" alt="" class="brand-img">
                        <h3>Inventory System</h3>
                    </div>
                    <div class="mobile menu-burger">
                        <i class='bx bx-menu '></i>
                    </div>
                </div>
                <div class="menu-bar">
                    <div class="menu">
                        <ul class="menu-links">
                            <li class="menu-link {% block nav_dashboard %}{% endblock %}"><i class='nav-icon bx bx-home'></i><a href="{{ url_for('dashboard') }}">Dashboard</a></li>
                            <li class="menu-link {% block nav_inventory %}{% endblock %}"><i class='nav-icon bx bxs-package'></i><a href="{{ url_for('product.index') }}">Products</a></li>
                            <li class="menu-link {% block nav_category %}{% endblock %}"><i class='nav-icon bx bxs-category' ></i><a href="{{ url_for('category.index') }}">Category</a></li>
                            <li class="menu-link {% block nav_supplier %}{% endblock %}"><i class='nav-icon bx bxs-buildings' ></i><a href="{{ url_for('supplier.index') }}">Supplier</a></li>
                            <li class="menu-link {% block nav_report %}{% endblock %}"><i class='nav-icon bx bx-line-chart' ></i><a href="{{ url_for('sale.sales_index') }}">Sales</a></li>
                            <li class="menu-link {% block nav_checkout %}{% endblock %}"><i class='nav-icon bx bx-dollar-circle' ></i><a href="{{ url_for('sale.show_checkout_page') }}">Check Out</a></li>
                            <li class="menu-link {% block nav_cashflow %}{% endblock %}"><i class='nav-icon bx bx-book-content'></i><a href="{{url_for('cashflow.index')}}">Cash Flow</a></li>
                            <li class="menu-link {% block nav_ImExport %}{% endblock %}"><i class='nav-icon bx bx-transfer'></i><a href="{{url_for('main.imexport_overview')}}">Import & Export</a></li>
                            {% for role in current_user.roles if role.name == 'admin' %}
                                <li class="menu-link {% block nav_staff %}{% endblock %}"><i class='nav-icon bx bxs-group' ></i><a href="{{ url_for('user.index') }}">Staff</a></li>
                            {% endfor %}
                            <li class="menu-link {% block nav_profile %}{% endblock %}"><i class='nav-icon bx bx-user-circle'></i><a href="{{url_for('user.get_staff',id=current_user.id)}}">Profile</a></li>
                        </ul>
                    </div>
                    <div class="bottom-content logout">
                        <div class="flex" style="color: #fff !important;">
                            <i class='bx bx-log-out'></i><a style="color: #fff !important;" href="{{url_for('auth.logout')}}" onclick="return confirm('Log out immediately?')">Logout</a>
                        </div>
                    </div>
                </div>
                
            </div>
        </aside>

       <div class="main">
            <header class="main-header">
                <div class="left-nav">
                    <div class="menu-burger">

                        <i class='bx bx-menu '></i>
                    </div>
                    <p>{% block nav_title %}{% endblock %}</p>
                </div>
                
                <div class="right-nav flex flex-center-center">
                    <span>Welcome! <b>{{current_user.Last_Name + ' ' + current_user.First_Name}}</b></span>
                </div>
            </header>
            <div class="main-container">
                    {% block content %} {% endblock %}
            </div>
        </div> 
    </div>
   
    <script>
        const hamburger = document.querySelectorAll(".menu-burger");
        const main = document.querySelector(".main");
        var asside = document.getElementById("aside");
        var root = document.documentElement;

        hamburger.forEach((hamburger)=>{

            hamburger.addEventListener("click",()=>{
                
                if (asside.classList.contains("opened")) { 
                    console.log("yes")
                    asside.classList.remove("opened");
                    main.classList.toggle("full-page")
                }else{
                    asside.classList.toggle("opened");
                    
                    main.classList.remove("full-page")
                }
                // root.style.setProperty('--sidebar-width', '0%');
            })
        })
    

    </script>
    <script src="DataTables/datatables.min.js">
            
        new DataTable('#example');
    </script>
    <script>
        // $(document).ready(function () {
        //     $('#data').DataTable({
        //         columns: [
        //         null,
        //         {searchable: false},
        //         {orderable: false, searchable: false},
        //         {orderable: false, searchable: false},
        //         null],
        //     });
        // });
    </script>

    {% block jscontent %}{% endblock %}
    </body>
    </html>

app/templates/cashflow.html
{% extends 'base.html' %}
{% block nav_title %} Cash Flow{% endblock %}
{% block nav_cashflow %}active{% endblock %}
{% block css_style %}
    <link rel="stylesheet" href="{{url_for('static',filename='css/table.css')}}"> 
    <link rel="stylesheet" href="{{url_for('static',filename='css/form.css')}}"> 
    <link rel="stylesheet" href="{{url_for('static',filename='css/flex.css')}}"> 
    <link rel="stylesheet" href="{{url_for('static',filename='css/grid.css')}}"> 
    <link rel="stylesheet" href="{{url_for('static',filename='css/button.css')}}">
    <style>
        .card{
            min-width: 300px;
        }
    </style>
{% endblock %}

{% block content %}

<h2 style="text-align: left;">{{date}}</h2>
<div class="grid-container four-two-grid">
    <div class="card" style="max-height: 763px; overflow-y: scroll;">
        <table>
            <tr>
                <th>Date</th>
                <th>Particulars</th>
                <th>Debit</th>
                <th>Credit</th>
                <th>Balance</th>
                <th>Action</th>
            </tr>
            {% for row in cashflows %}
            <tr>
                <td>{{row.date}}</td>
                <td>{{row.particulars}}</td>
                <td>{% if row.debit %}{{"%.2f"|format(row.debit)}}{% else %} 0 {% endif %}</td>
                <td>{% if row.credit %}{{"%.2f"|format(row.credit)}}{% else %} 0 {% endif %}</td>
                <td>{% if row.balance %}{{"%.2f"|format(row.balance)}}{% else %} 0 {% endif %}</td>

                <td>{% if row.particulars != "balance b/f" %}<a href="{{url_for('cashflow.record_detail',id=row.id)}}">view</a> {% endif %}</td>
            </tr>
            
            {% endfor %}
        </table>
    </div>
    <div class="flex flex-center-center flex-direction-column">
        <div class="card" style="justify-content: space-evenly  !important;">
            <div class="card-header">Select Year and Month</div>
            <div class="card-contents">

                <form action="{{url_for('cashflow.index',id=current_user.id)}}" method='get'>
                    
                    <input type="month" name="date" value="{{date}}" />
                    <input type="submit" class="button success" value="Search">
                </form>
            </div>
        </div>
        <br>
        {% for role in current_user.roles if role.name == 'admin' %}
        
        <div class="card">
            <div class="card-header">
                <div class="flex flex-between-center">

                    <p id="switch-text">Insert records</p>
                </div>
            </div>
            <div class="card-contents">
                <form action="{{url_for('cashflow.insert_cashflow')}}" id="insert-form" method="post" >
                    <label for="particulars">Particulars</label>
                    <input type="text" placeholder="particulars" name="particulars">
                    <label for="date">Date</label>
                    <input type="date" name="new_date" id="date" required>
                    <label for="">Time</label>
                    <input type="time" name="new_time" id="time" step="2" required>
                    <label for="particulars">Debit</label>
                    <input type="number" placeholder="debit" name="debit" value="0" min="0.00" step="0.01" required>    
                    <label for="particulars">Credit</label>
                    <input type="number" placeholder="credit" name="credit" value="0" min="0.00" step="0.01" required>
                    <label for="particulars">Remarks</label>
                    <textarea type="text" placeholder="remarks" value="" name="remark" style=" resize: none;" rows="4"></textarea>
                    <input type="submit" class="button success" value="Add">
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block jscontent %}

{% endblock %}

app/templates/cashflow_detail.html
{% extends 'base.html' %}
{% block nav_title %} Cashflow Overview > <a href="{{url_for('cashflow.record_detail',id=cashflow.id)}}">Cashflow</a>{% endblock %}
{% block nav_cashflow %}active{% endblock %}
{% block css_style %}
    <link rel="stylesheet" href="{{url_for('static',filename='css/table.css')}}"> 
    <link rel="stylesheet" href="{{url_for('static',filename='css/form.css')}}"> 
    <link rel="stylesheet" href="{{url_for('static',filename='css/flex.css')}}"> 
    <link rel="stylesheet" href="{{url_for('static',filename='css/grid.css')}}"> 
    <link rel="stylesheet" href="{{url_for('static',filename='css/button.css')}}"> 
    <style>
        .card{
            max-width:600px
        }
        .card > .card-contents >div.flex>form{
            min-width: 250px;
            padding: 10px 20px 10px 10px;
        }

        @media (max-width: 550px) {
            form.flex{
                width: 100%;
            }
            textarea{
                width: 100% !important;
            }
        }
    </style>
{% endblock %}

{% block content %}
<a href="{{url_for('cashflow.index')}}"><b>Go Back</b></a><br><br>
<div class="card">
    <div class="card-header">

        <h3 style="text-align: center;"><b>{{cashflow.particulars}}</b></h3>
    </div>
    <div class="card-contents">
        
        <p>Date: {{cashflow.date}}</p>
        <p>Debit: RM {{"%.2f"|format(cashflow.debit)}}     |     Credit: RM {{"%.2f"|format(cashflow.credit)}}</p>
        <p>Balance: RM {{"%.2f"|format(cashflow.balance)}}</p>
        <br>
        <p>Remarks: <span>{{cashflow.remarks}}</span></p>
    </div>
    <div class="card-bottom flex flex-end-center">
        {% for role in current_user.roles if role.name == 'admin' %}<a href="{{url_for('cashflow.delete_cashflow',cashflow_id = cashflow.id)}}" style="color: red;">Delete record</a>{% endfor %}
    </div>
        
</div>
<br>
{% for role in current_user.roles if role.name == 'admin' %}

<div class="card">
    <div class="card-header">
        <h4 style="text-align: center;"><b>UPDATE </b>FORM</h4>
    </div>
    <div class="card-contents">

        <div class="flex flex-direction-row">
            <form action="{{url_for('cashflow.update_record',id=cashflow.id)}}" method="post" class="flex flex-direction-column">

                <label for="particular">Particular</label>
                <input type="text" name="new_particular" id="" placeholder="{{cashflow.particulars}}" value="{{cashflow.particulars}}" required>
                
                <label for="debit">Debit</label>
                <input type="number" name="new_debit" id="" value="{{"%.2f"|format(cashflow.debit)}}" min="0" step="0.01" required>
                <label for="credit">Credit</label>
                <input type="number" name="new_credit" id="" value="{{"%.2f"|format(cashflow.credit)}}" min="0" step="0.01" required>
                <label for="remark">Remark</label>
                <textarea name="new_remark" id="remark" rows="10" style="width: 250px; min-width: 150px; max-width: 500px;">{{cashflow.remarks}}</textarea>
                <input class="button success" type="submit" value="Update">
            </form>
            

            <form class="flex flex-direction-column" method="post" action="{{url_for('cashflow.update_cashflow_date',id=cashflow.id)}}">

                <label for="date">Date</label>
                
                <div class="">
                    
                    <label for="chk_specific_time">Define Specific Time:<input type="checkbox" id="chk_time" style="margin-left: 5px; width: 30px;"></label>
                    <!-- <input type="date" name="new_date" id="new_date" value="{{cashflow.date.date()}}" disabled> -->
                    <input type="date" name="new_date" id="new_date" value="{{cashflow.date.date()}}" disabled required>
                    <input type="time" name="new_time" id="new_time" value="{{cashflow.date.time()}}"disabled required >
                </div>
                <br>
                <input class="button info" type="submit" value="Change Time" id="btn-changetime" disabled>
            </form>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}


{% block jscontent %}

    <script>
        document.getElementById('chk_time').addEventListener('change',(e)=>{
            var new_date = document.getElementById('new_date')
            var new_time = document.getElementById('new_time')
            var timebtn = document.getElementById('btn-changetime')

            if (e.target.checked) {
                new_date.disabled = false;
                new_time.disabled = false;
                timebtn.disabled = false;
            } else {
                new_date.disabled = true;
                new_time.disabled = true;
                timebtn.disabled = true;
            }
        })
    </script>
{% endblock %}

app/templates/cashflow_report.html
{% extends 'base.html' %}
{% block nav_title %} Cashflow Overview > <a href="{{url_for('main.cashflow_report')}}"> Report</a>{% endblock %}
{% block nav_ImExport %}active{% endblock %}
{% block css_style %}

{% endblock %}
{% block content %}
<form action="{{url_for("main.generate_cashflow_report")}}" method="get">
    <label for="date">Select Date:</label>
    <input type="month" name="date" required>
    <input type="submit" value="Generate Report">
</form>
{% endblock %}

app/templates/inventory_report.html
{% extends 'base.html' %}
{% block nav_ImExport %}active{% endblock %}
{% block css_style %}

{% endblock %}
{% block content %}
<h3>Generate by StockIn Date</h3>
<br>
<form action="{{url_for("main.generate_inventory_report")}}" method="get">
    <label for="product">Product: </label>
    <select name="product" id="">
        {% for product in products %}
        <option value="{{product.Name}}">{{product.Name}}</option>
        {% endfor %}
    </select>

    <label for="fromdate">From Date:</label>
    <input type="date" name="from_date" required>

    <label for="todate">To Date:</label>
    <input type="date" name="to_date" required>

    
    <input type="submit" value="Generate Report">
</form>
{% endblock %}

app/templates/preloader.html
{% block preloader %}
<div id="preloader"></div>
<script src="{{url_for('static', filename='/js/pre-loader.js')}}"></script>
{% endblock %}